#!/bin/sh
# shellcheck shell=ash  # BusyBox ash target — local is supported
# shellcheck disable=SC3043
# Spike T2.0 P0: mss_dump / bst_dump decode-oracle tests.
#
# Compiles both dumpers from source and runs them over the committed
# synthetic container fixtures (tests/fixtures/transmute/, generated by
# tools/transmute/gen_fixtures.py). The fixtures transcribe the pinned
# formats from cms/mapping_mesen2_bsnes.json; the dumpers transcribe the
# vendored serialize sources — a clean zero-residual walk cross-checks
# the two transcriptions field-for-field. Semantic (emulator-produced)
# fixtures arrive with the SuperForge StateProbe import; these tests
# cover container framing, record/RLE codecs, load gates, refuse paths,
# and dump stability.
#
# Desktop-tier tool tests: they need cc + zlib headers (like the rzip
# interop suite). They never write into the repo tree.
set -e

TESTS_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
PROJECT_ROOT="$(cd "$TESTS_DIR/.." && pwd)"
TRANSMUTE="$PROJECT_ROOT/tools/transmute"
FIXTURES="$TESTS_DIR/fixtures/transmute"

passed=0
failed=0

assert_eq() {
    local desc expected actual
    desc="$1"; expected="$2"; actual="$3"
    if [ "$expected" = "$actual" ]; then
        passed=$((passed + 1))
    else
        printf 'FAIL: %s\n  expected: [%s]\n  actual:   [%s]\n' \
            "$desc" "$expected" "$actual" >&2
        failed=$((failed + 1))
    fi
}

# --- Setup: build both dumpers into the test tmpdir ---
TEST_TMPDIR=$(mktemp -d)
trap 'rm -rf "$TEST_TMPDIR"' EXIT

if ! gcc -std=c99 -O2 -Wall -o "$TEST_TMPDIR/mss_dump" \
        "$TRANSMUTE/mss_dump.c" -lz 2>"$TEST_TMPDIR/cc.err"; then
    printf 'FAIL: cannot build mss_dump:\n' >&2
    cat "$TEST_TMPDIR/cc.err" >&2
    printf '\n0 passed, 1 failed\n'
    exit 1
fi
if ! gcc -std=c99 -O2 -Wall -o "$TEST_TMPDIR/bst_dump" \
        "$TRANSMUTE/bst_dump.c" -lz 2>"$TEST_TMPDIR/cc.err"; then
    printf 'FAIL: cannot build bst_dump:\n' >&2
    cat "$TEST_TMPDIR/cc.err" >&2
    printf '\n0 passed, 1 failed\n'
    exit 1
fi
MSS="$TEST_TMPDIR/mss_dump"
BST="$TEST_TMPDIR/bst_dump"

# --- Fixture integrity: committed bytes match the pinned manifest ---
if (cd "$FIXTURES" && sha256sum -c fixtures.sha256 >/dev/null 2>&1); then
    passed=$((passed + 1))
else
    printf 'FAIL: fixtures.sha256 mismatch — fixtures drifted from manifest\n' >&2
    failed=$((failed + 1))
fi

# --- mss_dump: valid fixture decodes, planted values surface ---
rc=0
"$MSS" "$FIXTURES/synthetic_v0.mss" >"$TEST_TMPDIR/mss1.out" 2>&1 || rc=$?
assert_eq "mss v0 exit code" "0" "$rc"
assert_eq "mss v0 console type line" "mss.console_type = 0" \
    "$(grep '^mss.console_type' "$TEST_TMPDIR/mss1.out")"
assert_eq "mss v0 planted cpu.a record" "1" \
    "$(grep -c "^cpu.a	2	0x1234	4660$" "$TEST_TMPDIR/mss1.out")"
assert_eq "mss v0 rom name" "mss.rom_name = stateprobe.sfc" \
    "$(grep '^mss.rom_name' "$TEST_TMPDIR/mss1.out")"
assert_eq "mss v0 record count" "12" \
    "$(grep -c '	' "$TEST_TMPDIR/mss1.out")"

# --- mss_dump: dump stability (byte-identical across runs) ---
"$MSS" "$FIXTURES/synthetic_v0.mss" >"$TEST_TMPDIR/mss2.out" 2>&1 || true
if cmp -s "$TEST_TMPDIR/mss1.out" "$TEST_TMPDIR/mss2.out"; then
    passed=$((passed + 1))
else
    printf 'FAIL: mss_dump output not stable across runs\n' >&2
    failed=$((failed + 1))
fi

# --- mss_dump: chip firewall refuses, truncation fails loudly ---
rc=0
"$MSS" "$FIXTURES/synthetic_chipcart.mss" >/dev/null 2>&1 || rc=$?
assert_eq "mss chip-cart refuse exit" "2" "$rc"
rc=0
"$MSS" "$FIXTURES/synthetic_truncated.mss" >/dev/null 2>&1 || rc=$?
assert_eq "mss truncated malformed exit" "1" "$rc"

# --- bst_dump: valid fixture walks to exactly zero residual ---
rc=0
"$BST" -s 8192 "$FIXTURES/synthetic_v0.bst" >"$TEST_TMPDIR/bst1.out" 2>&1 || rc=$?
assert_eq "bst v0 exit code" "0" "$rc"
assert_eq "bst v0 stream size" "bst.stream_size = 290423" \
    "$(grep '^bst.stream_size' "$TEST_TMPDIR/bst1.out")"
assert_eq "bst v0 version gate" "header.version = 115.1" \
    "$(grep '^header.version' "$TEST_TMPDIR/bst1.out")"
assert_eq "bst v0 planted wdc.a" "cpu.wdc.a = 0x1234 (4660)" \
    "$(grep '^cpu.wdc.a ' "$TEST_TMPDIR/bst1.out")"
assert_eq "bst v0 planted htime" "cpu.io.htime = 0x800 (2048)" \
    "$(grep '^cpu.io.htime ' "$TEST_TMPDIR/bst1.out")"
assert_eq "bst v0 planted apu0" "smp.io.apu0 = 0xaa (170)" \
    "$(grep '^smp.io.apu0 ' "$TEST_TMPDIR/bst1.out")"
assert_eq "bst v0 dsp blob present" "1" \
    "$(grep -c '^dsp.spc_dsp_blob : 640 bytes' "$TEST_TMPDIR/bst1.out")"

# --- bst_dump: dump stability ---
"$BST" -s 8192 "$FIXTURES/synthetic_v0.bst" >"$TEST_TMPDIR/bst2.out" 2>&1 || true
if cmp -s "$TEST_TMPDIR/bst1.out" "$TEST_TMPDIR/bst2.out"; then
    passed=$((passed + 1))
else
    printf 'FAIL: bst_dump output not stable across runs\n' >&2
    failed=$((failed + 1))
fi

# --- bst_dump: gates and firewall ---
rc=0
"$BST" -s 8192 "$FIXTURES/synthetic_sync0.bst" >/dev/null 2>&1 || rc=$?
assert_eq "bst synchronize=0 refuse exit" "2" "$rc"
rc=0
"$BST" -s 8192 "$FIXTURES/synthetic_chipresidual.bst" >/dev/null 2>&1 || rc=$?
assert_eq "bst chip-residual refuse exit" "2" "$rc"
rc=0
"$BST" "$FIXTURES/synthetic_v0.bst" >/dev/null 2>&1 || rc=$?
assert_eq "bst wrong sram size refuses" "2" "$rc"

# --- both: usage errors are loud ---
rc=0
"$MSS" >/dev/null 2>&1 || rc=$?
assert_eq "mss usage error exit" "1" "$rc"
rc=0
"$BST" >/dev/null 2>&1 || rc=$?
assert_eq "bst usage error exit" "1" "$rc"

# --- REAL-file oracle: StateProbe beacon capture (Mesen2 2.1.1) ---
# tests/fixtures/transmute/stateprobe/ — emulator-produced fixture; see
# its README. Asserts on decoded content only, never fixture bytes.
SP="$TESTS_DIR/fixtures/transmute/stateprobe"

# identity discipline (H7): the committed ROM must hash to a value the
# manifest declares
rom_hash="$(sha256sum "$SP/stateprobe.sfc" | cut -d' ' -f1)"
if grep -q "$rom_hash" "$SP/stateprobe_manifest.json"; then
    passed=$((passed + 1))
else
    printf 'FAIL: stateprobe.sfc sha256 %s not found in manifest\n' \
        "$rom_hash" >&2
    failed=$((failed + 1))
fi

rc=0
"$MSS" "$SP/beacon_gen2.mss" >"$TEST_TMPDIR/real1.out" 2>&1 || rc=$?
assert_eq "real mss exit code" "0" "$rc"
assert_eq "real mss emu version (2.1.1 = pin)" "mss.emu_version = 131329" \
    "$(grep '^mss.emu_version' "$TEST_TMPDIR/real1.out")"
assert_eq "real mss console type" "mss.console_type = 0" \
    "$(grep '^mss.console_type' "$TEST_TMPDIR/real1.out")"
assert_eq "real mss record count" "1344" \
    "$(grep -c '	' "$TEST_TMPDIR/real1.out")"
assert_eq "real mss SPC at instruction boundary (quiescent rule)" \
    "spc.opStep	1	0x0	0" \
    "$(grep '^spc.opStep	' "$TEST_TMPDIR/real1.out")"
assert_eq "real mss no in-flight port write (quiescent rule)" \
    "spc.pendingCpuRegUpdate	1	0x0	0" \
    "$(grep '^spc.pendingCpuRegUpdate	' "$TEST_TMPDIR/real1.out")"
assert_eq "real mss sram size matches cart declaration" "8192" \
    "$(grep '^cart.saveRam	' "$TEST_TMPDIR/real1.out" | cut -f2)"

# RESULT_SCHEMA v1 block via extraction mode: magic at WRAM $7EF000
# (offset 0xF000 = 61440), beacon $A5 at $7EF7F0 (offset 63472)
"$MSS" -x memoryManager.workRam "$SP/beacon_gen2.mss" \
    >"$TEST_TMPDIR/wram.bin" 2>/dev/null || true
assert_eq "extracted wram size" "131072" \
    "$(wc -c <"$TEST_TMPDIR/wram.bin" | tr -d ' ')"
magic="$(dd if="$TEST_TMPDIR/wram.bin" bs=1 skip=61440 count=4 \
    2>/dev/null)"
assert_eq "result block magic in wram" "SPRB" "$magic"
beacon="$(dd if="$TEST_TMPDIR/wram.bin" bs=1 skip=63472 count=1 \
    2>/dev/null | od -An -tx1 | tr -d ' \n')"
assert_eq "capture beacon byte" "a5" "$beacon"

rc=0
"$MSS" -x no.such.key "$SP/beacon_gen2.mss" >/dev/null 2>&1 || rc=$?
assert_eq "extraction miss exit" "3" "$rc"

# stability on the real file
"$MSS" "$SP/beacon_gen2.mss" >"$TEST_TMPDIR/real2.out" 2>&1 || true
if cmp -s "$TEST_TMPDIR/real1.out" "$TEST_TMPDIR/real2.out"; then
    passed=$((passed + 1))
else
    printf 'FAIL: real-file dump not stable across runs\n' >&2
    failed=$((failed + 1))
fi

printf '\n%d passed, %d failed\n' "$passed" "$failed"
[ "$failed" -eq 0 ]
